name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2

    - name: Install dotenv
      run: npm install dotenv

    - name: Run JavaScript
#       run: node index.js
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}
        MY_VAR: ${{ secrets.MY_VAR }}
